curl -v "http://localhost/"
curl -v "http://localhost/test"
curl -v "http://localhost/json"
curl -v "http://localhost/demo/v1/user/xxxxx/info?token=xxxx"
curl -v "http://localhost/list_para?p1=a&p2=b&p3=c" -d "p1=a"