curl -v "http://localhost/"
curl -v "http://localhost/test"
curl -v "http://localhost/json"
curl -v "http://localhost/demo/v1/user/xxxxx/info?token=xxxx"
curl -vX POST "http://localhost/demo/v1/user/token" -d "userId=albaro&passwd=xx"
curl -v "http://localhost/test2?username=Albaro"
